# -*- coding: utf-8 -*-
# Contenu du site Mon Premier Livre

PRODUCTS = [
    {
        "slug": "la-ferme-des-copains",
        "name": "La ferme des copains",
        "name_en": "Farmyard friends",
        "price": 30.00,
        "age": "6 mois - 3 ans",
        "age_en": "6 months - 3 years",
        "short": "Un livre en feutrine tout doux à déchirer, pour découvrir les animaux de la ferme du bout des doigts.",
        "short_en": "A soft tearable felt book for discovering farm animals with little fingers.",
        "long": "« La ferme des copains » est un livre 100% feutrine, pensé pour les petites mains curieuses. Chaque page peut être délicatement déchirée puis rattachée grâce à une bande auto-agrippante, pour un jeu sans fin qui muscle la motricité fine. Bébé y découvre la vache, le mouton, le cochon et la poule à travers des formes simples et des couleurs douces, dans des tons Morandi apaisants qui n'agressent pas le regard. Sans danger, sans bruit de papier, ce livre accompagne les tout premiers instants de lecture et devient vite un doudou-livre que l'on retrouve partout.",
        "long_en": "“Farmyard friends” is a 100% felt book designed for curious little hands. Each page can be gently torn off and reattached with a hook-and-loop strip, for endless play that builds fine motor skills. Baby discovers the cow, the sheep, the pig and the hen through simple shapes and gentle Morandi tones that are easy on the eyes. Safe, silent (no paper rustling), this book accompanies the very first moments of reading and quickly becomes a comfort book carried everywhere.",
        "care": "Lavable en machine à 30°C, cycle délicat. Ne pas mettre au sèche-linge.",
        "care_en": "Machine washable at 30°C, delicate cycle. Do not tumble dry.",
        "tags": ["animaux", "premiers mois", "best-seller"],
        "image": "assets/products/la-ferme-des-copains.png",
    },
    {
        "slug": "sous-la-mer",
        "name": "Sous la mer",
        "name_en": "Under the sea",
        "price": 30.00,
        "age": "1 - 4 ans",
        "age_en": "1 - 4 years",
        "short": "Un voyage sensoriel parmi les poissons, les vagues et les coquillages en feutrine texturée.",
        "short_en": "A sensory journey among fish, waves and shells in textured felt.",
        "long": "« Sous la mer » invite les tout-petits à explorer un monde aquatique tout en douceur : des vagues à froisser, un poisson à déchirer et recoller, une étoile de mer à caresser. Les textures variées stimulent le toucher et la curiosité, pendant que les couleurs bleu poudré et sable évoquent le calme de l'océan. Un livre pensé pour être manipulé sans crainte, encore et encore.",
        "long_en": "“Under the sea” invites little ones to gently explore an underwater world: waves to crinkle, a fish to tear off and reattach, a starfish to stroke. The varied textures stimulate touch and curiosity, while the powder-blue and sand tones evoke the calm of the ocean. A book designed to be handled fearlessly, again and again.",
        "care": "Lavable en machine à 30°C, cycle délicat. Séchage à plat recommandé.",
        "care_en": "Machine washable at 30°C, delicate cycle. Flat drying recommended.",
        "tags": ["ocean", "sensoriel"],
        "image": "assets/products/sous-la-mer.png",
    },
    {
        "slug": "mes-premieres-couleurs",
        "name": "Mes premières couleurs",
        "name_en": "My first colours",
        "price": 30.00,
        "age": "6 mois - 2 ans",
        "age_en": "6 months - 2 years",
        "short": "Un imagier tout en feutrine pour apprivoiser les couleurs en douceur, une page à la fois.",
        "short_en": "A felt picture book for gently learning colours, one page at a time.",
        "long": "Chaque page de cet imagier présente une couleur associée à un objet du quotidien (une pomme rouge, un ciel bleu, une feuille verte). Les pages détachables encouragent la préhension et le jeu libre, pendant qu'un adulte peut nommer les couleurs à voix haute. Un premier vocabulaire qui se construit par le jeu et le toucher, loin des écrans.",
        "long_en": "Each page of this picture book shows a colour linked to an everyday object (a red apple, a blue sky, a green leaf). The detachable pages encourage grasping and free play, while an adult can name the colours out loud. A first vocabulary built through play and touch, far from screens.",
        "care": "Lavable en machine à 30°C, cycle délicat.",
        "care_en": "Machine washable at 30°C, delicate cycle.",
        "tags": ["couleurs", "premiers mois", "best-seller"],
        "image": "assets/products/mes-premieres-couleurs.png",
    },
    {
        "slug": "le-potager-de-mnamie",
        "name": "Le potager de mamie",
        "name_en": "Grandma's vegetable patch",
        "price": 30.00,
        "age": "1 - 4 ans",
        "age_en": "1 - 4 years",
        "short": "Des légumes en feutrine à récolter et déchirer, pour découvrir la nature du bout des doigts.",
        "short_en": "Felt vegetables to harvest and tear off, for discovering nature with little fingers.",
        "long": "Carotte, tomate, courgette : ce livre transforme le potager en terrain de jeu tactile. Les pages, à déchirer et refixer, imitent le geste de la récolte et donnent du sens au vocabulaire du jardin. Un bel outil pour parler d'alimentation et de nature dès le plus jeune âge, dans des teintes chaleureuses et naturelles.",
        "long_en": "Carrot, tomato, courgette: this book turns the vegetable patch into a tactile playground. The pages, made to be torn off and reattached, mimic the gesture of harvesting and give meaning to garden vocabulary. A lovely tool for talking about food and nature from the earliest age, in warm, natural tones.",
        "care": "Lavable en machine à 30°C, cycle délicat.",
        "care_en": "Machine washable at 30°C, delicate cycle.",
        "tags": ["nature", "vocabulaire"],
    },
    {
        "slug": "mon-corps-et-moi",
        "name": "Mon corps et moi",
        "name_en": "My body and me",
        "price": 30.00,
        "age": "1 - 3 ans",
        "age_en": "1 - 3 years",
        "short": "Un livre en feutrine pour nommer les parties du corps et développer la conscience de soi.",
        "short_en": "A felt book for naming body parts and building self-awareness.",
        "long": "À travers des silhouettes douces et des pages à manipuler, l'enfant apprend à nommer sa tête, ses mains, ses pieds. Un support idéal pour accompagner l'autonomie et la confiance en soi dès les premiers mois, en complément des comptines et jeux du quotidien.",
        "long_en": "Through soft silhouettes and pages to handle, the child learns to name their head, hands and feet. An ideal tool for supporting independence and self-confidence from the earliest months, alongside everyday songs and games.",
        "care": "Lavable en machine à 30°C, cycle délicat.",
        "care_en": "Machine washable at 30°C, delicate cycle.",
        "tags": ["corps", "vocabulaire"],
    },
    {
        "slug": "petites-emotions",
        "name": "Petites émotions",
        "name_en": "Little feelings",
        "price": 30.00,
        "age": "2 - 5 ans",
        "age_en": "2 - 5 years",
        "short": "Un livre en feutrine pour mettre des mots doux sur les grandes émotions des tout-petits.",
        "short_en": "A felt book for putting gentle words on little ones' big feelings.",
        "long": "Joie, colère, tristesse, surprise : chaque page illustre une émotion avec des expressions simples et des textures à explorer. Un support précieux pour les parents qui souhaitent ouvrir le dialogue émotionnel dès le plus jeune âge, dans la douceur et sans jugement.",
        "long_en": "Joy, anger, sadness, surprise: each page illustrates an emotion with simple expressions and textures to explore. A precious tool for parents who want to open emotional dialogue from an early age, with gentleness and without judgement.",
        "care": "Lavable en machine à 30°C, cycle délicat.",
        "care_en": "Machine washable at 30°C, delicate cycle.",
        "tags": ["émotions", "nouveauté"],
        "image": "assets/products/petites-emotions.png",
    },
    {
        "slug": "la-meteo-du-jour",
        "name": "La météo du jour",
        "name_en": "Today's weather",
        "price": 30.00,
        "age": "2 - 5 ans",
        "age_en": "2 - 5 years",
        "short": "Soleil, pluie, nuages et vent à toucher, pour parler du temps qu'il fait chaque matin.",
        "short_en": "Sun, rain, clouds and wind to touch, for talking about the weather every morning.",
        "long": "Ce livre en feutrine accompagne le rituel matinal : quel temps fait-il aujourd'hui ? Les éléments à déchirer et replacer permettent de créer une routine ludique, idéale pour les crèches, les assistantes maternelles et la maison.",
        "long_en": "This felt book supports the morning ritual: what's the weather like today? The pieces, made to be torn off and put back, create a playful routine, ideal for nurseries, childminders and home.",
        "care": "Lavable en machine à 30°C, cycle délicat.",
        "care_en": "Machine washable at 30°C, delicate cycle.",
        "tags": ["routine", "nouveauté"],
    },
    {
        "slug": "abc-en-feutrine",
        "name": "ABC en feutrine",
        "name_en": "Felt ABC",
        "price": 30.00,
        "age": "3 - 6 ans",
        "age_en": "3 - 6 years",
        "short": "Un premier abécédaire tout doux pour apprivoiser les lettres avant l'entrée à l'école.",
        "short_en": "A gentle first alphabet book for getting to know letters before starting school.",
        "long": "Chaque lettre est associée à une texture et un petit mot illustré en feutrine, pour une première approche ludique et sensorielle de l'alphabet. Un bel objet transitionnel entre le livre-jeu de la petite enfance et les premiers apprentissages de la lecture.",
        "long_en": "Each letter is paired with a texture and a small illustrated felt word, for a first playful and sensory approach to the alphabet. A lovely transitional object between the play-books of early childhood and the first steps of learning to read.",
        "care": "Lavable en machine à 30°C, cycle délicat.",
        "care_en": "Machine washable at 30°C, delicate cycle.",
        "tags": ["alphabet", "best-seller"],
        "image": "assets/products/abc-en-feutrine.png",
    },
    {
        "slug": "au-dodo-petit-lapin",
        "name": "Au dodo, petit lapin",
        "name_en": "Off to sleep, little rabbit",
        "price": 30.00,
        "age": "6 mois - 3 ans",
        "age_en": "6 months - 3 years",
        "short": "Un livre-doudou en feutrine pour accompagner le rituel du coucher en toute douceur.",
        "short_en": "A cuddly felt book for gently accompanying the bedtime ritual.",
        "long": "Une histoire toute simple pour préparer le sommeil : le petit lapin ferme les volets, enfile son pyjama, retrouve son doudou. Les pages en feutrine, agréables au toucher, apaisent et rassurent au moment du coucher, sans écran ni lumière stimulante.",
        "long_en": "A very simple story to prepare for sleep: the little rabbit closes the shutters, puts on pyjamas, finds their comfort toy. The felt pages, pleasant to touch, soothe and reassure at bedtime, with no screen or stimulating light.",
        "care": "Lavable en machine à 30°C, cycle délicat.",
        "care_en": "Machine washable at 30°C, delicate cycle.",
        "tags": ["coucher", "doudou"],
        "image": "assets/products/au-dodo-petit-lapin.png",
    },
]

FAQ = {
    "Commande": [
        ("Comment passer une commande sur Mon Premier Livre ?",
         "Ajoutez le ou les livres souhaités à votre panier, puis suivez les étapes indiquées jusqu'à la validation du paiement. Vous recevrez un e-mail de confirmation dès que votre commande sera enregistrée.",
         "How do I place an order on Mon Premier Livre?",
         "Add the book or books you want to your cart, then follow the steps through to payment confirmation. You will receive a confirmation e-mail as soon as your order is registered."),
        ("Puis-je modifier ma commande après validation ?",
         "Contactez-nous le plus vite possible à monpremierlivre.com@gmail.com : nous ferons notre possible pour modifier votre commande tant qu'elle n'est pas encore expédiée.",
         "Can I change my order after confirming it?",
         "Contact us as soon as possible at monpremierlivre.com@gmail.com: we will do our best to change your order as long as it has not yet been shipped."),
        ("Puis-je annuler ma commande ?",
         "Oui, tant que la commande n'a pas été expédiée. Écrivez-nous rapidement et nous procéderons à l'annulation et au remboursement intégral.",
         "Can I cancel my order?",
         "Yes, as long as the order has not been shipped. Write to us quickly and we will cancel it and issue a full refund."),
        ("Est-il possible de commander sans créer de compte ?",
         "La création d'un compte permet de suivre vos commandes et de profiter de votre réduction de bienvenue, mais nous proposons également une option de commande simplifiée pour les clientes pressées.",
         "Can I order without creating an account?",
         "Creating an account lets you track your orders and enjoy your welcome discount, but we also offer a simplified checkout option for customers in a hurry."),
        ("Comment savoir si un livre est disponible en stock ?",
         "Si vous parvenez à passer commande sur notre site, c'est que le livre est en stock.",
         "How do I know if a book is in stock?",
         "If you're able to complete your order on our website, the book is in stock."),
        ("Puis-je commander plusieurs livres identiques ?",
         "Bien sûr, ajustez simplement la quantité souhaitée sur la fiche produit avant de l'ajouter au panier.",
         "Can I order several copies of the same book?",
         "Of course, simply adjust the quantity you want on the product page before adding it to your cart."),
        ("Proposez-vous des coffrets ou des lots de livres ?",
         "Des coffrets thématiques regroupant plusieurs livres en feutrine sont proposés régulièrement, notamment en période de fêtes. Abonnez-vous à notre newsletter pour ne rien manquer.",
         "Do you offer gift sets or book bundles?",
         "Themed sets combining several felt books are offered regularly, especially around the holidays. Subscribe to our newsletter so you don't miss out."),
        ("J'ai reçu un e-mail de confirmation erroné, que faire ?",
         "Contactez notre service client avec votre numéro de commande, nous vérifierons et corrigerons l'erreur dans les plus brefs délais.",
         "I received an incorrect confirmation e-mail, what should I do?",
         "Contact our customer service with your order number, and we will check and correct the error as quickly as possible."),
        ("Comment suivre l'état d'avancement de ma commande ?",
         "Connectez-vous à votre compte dans la rubrique « Mes commandes » pour consulter le statut en temps réel : préparation, expédition, livraison.",
         "How can I track the progress of my order?",
         "Log in to your account and go to “My orders” to see the status in real time: preparation, shipping, delivery."),
    ],
    "Livraison": [
        ("Quels sont les délais de livraison ?",
         "Nos produits étant destinés aux tout-petits, nous effectuons un contrôle qualité rigoureux avant chaque expédition, afin de vous garantir un produit en toute sérénité. C'est pourquoi nos commandes sont généralement expédiées sous 48 à 72 heures — les bonnes choses méritent un peu de patience. Une fois la commande expédiée, vous pouvez la suivre directement depuis votre compte.",
         "What are the delivery times?",
         "Because our products are designed for babies and toddlers, we carry out a rigorous quality check before every shipment, to make sure you receive a product you can trust. That's why orders are usually shipped within 48 to 72 hours — good things are worth the wait. Once your order has shipped, you can track it directly from your account."),
        ("La livraison est-elle gratuite ?",
         "La livraison est offerte dès 80€ d'achat. En dessous de ce montant, des frais de port raisonnables sont appliqués et affichés avant validation du paiement.",
         "Is delivery free?",
         "Delivery is free from €80 of purchases. Below that amount, reasonable shipping fees apply and are shown before you confirm payment."),
        ("Livrez-vous en dehors de la France métropolitaine ?",
         "Oui, nous livrons partout dans le monde ! Vous pouvez ainsi offrir ce cadeau précieux à un proche, même à l'autre bout du monde.",
         "Do you deliver outside mainland France?",
         "Yes, we ship worldwide! So you can send this precious gift to a loved one, even on the other side of the world."),
        ("Puis-je suivre mon colis ?",
         "Un numéro de suivi vous est envoyé par e-mail dès l'expédition de votre commande, vous permettant de suivre le colis en temps réel.",
         "Can I track my parcel?",
         "A tracking number is e-mailed to you as soon as your order ships, letting you follow your parcel in real time."),
        ("Que faire si mon colis est perdu ou endommagé ?",
         "Contactez-nous avec votre numéro de commande : nous ouvrirons une enquête auprès du transporteur et vous proposerons un renvoi ou un remboursement.",
         "What if my parcel is lost or damaged?",
         "Contact us with your order number: we will open an inquiry with the carrier and offer you a reshipment or a refund."),
        ("Puis-je changer l'adresse de livraison après commande ?",
         "Si la commande n'a pas encore été expédiée, contactez-nous rapidement pour modifier l'adresse.",
         "Can I change the delivery address after ordering?",
         "If the order has not yet been shipped, contact us quickly to change the address."),
        ("Que se passe-t-il si je ne suis pas présente à la livraison ?",
         "Le transporteur laisse généralement un avis de passage ou dépose le colis en point relais, selon le mode choisi lors de la commande.",
         "What happens if I'm not there for delivery?",
         "The carrier usually leaves a delivery notice or drops the parcel at a pickup point, depending on the option chosen when ordering."),
    ],
    "Paiement": [
        ("Quels moyens de paiement acceptez-vous ?",
         "Nous acceptons la carte bancaire (Visa, Mastercard). Tous les paiements sont sécurisés.",
         "What payment methods do you accept?",
         "We accept credit cards (Visa, Mastercard). All payments are secure."),
        ("Mes données bancaires sont-elles sécurisées ?",
         "Oui, l'ensemble des transactions est chiffré et traité par un prestataire de paiement certifié. Nous ne stockons jamais vos données bancaires.",
         "Is my banking information secure?",
         "Yes, all transactions are encrypted and processed by a certified payment provider. We never store your banking details."),
        ("Puis-je utiliser un code promo ?",
         "Oui, un champ dédié est disponible lors du paiement pour saisir votre code de réduction.",
         "Can I use a promo code?",
         "Yes, a dedicated field is available at checkout for entering your discount code."),
        ("Pourquoi mon paiement a-t-il été refusé ?",
         "Cela peut provenir d'une erreur de saisie, d'un plafond de carte atteint ou d'un refus de votre banque. Contactez votre banque ou réessayez avec un autre moyen de paiement.",
         "Why was my payment declined?",
         "This can be due to a typing error, a card limit being reached, or a refusal by your bank. Contact your bank or try again with another payment method."),
        ("Vais-je recevoir une facture ?",
         "Oui, une facture est automatiquement générée et envoyée par e-mail après validation de votre commande.",
         "Will I receive an invoice?",
         "Yes, an invoice is automatically generated and e-mailed to you once your order is confirmed."),
        ("Puis-je payer avec une carte étrangère ?",
         "Oui, les cartes internationales sont acceptées sous réserve de validation par votre banque.",
         "Can I pay with a foreign card?",
         "Yes, international cards are accepted subject to approval by your bank."),
        ("Quand mon compte est-il débité ?",
         "Le débit est effectué au moment de la validation de la commande.",
         "When is my account charged?",
         "The charge is made when the order is confirmed."),
        ("Puis-je demander un remboursement partiel ?",
         "Oui, en cas de retour partiel d'une commande, le remboursement est ajusté au prorata des articles retournés.",
         "Can I request a partial refund?",
         "Yes, in the case of a partial return, the refund is adjusted in proportion to the items returned."),
        ("Combien de temps prend un remboursement ?",
         "Les remboursements sont traités sous 5 à 10 jours ouvrés après réception et vérification du retour.",
         "How long does a refund take?",
         "Refunds are processed within 5 to 10 business days after the return is received and checked."),
    ],
    "Produit & entretien": [
        ("En quelle matière sont fabriqués vos livres ?",
         "Nos livres sont confectionnés en feutrine douce, une matière textile résistante, sans danger et agréable au toucher pour les tout-petits.",
         "What material are your books made from?",
         "Our books are made from soft felt, a sturdy textile material that is safe and pleasant to the touch for little ones."),
        ("Les pages se déchirent-elles vraiment ?",
         "Oui, c'est le principe même de nos livres ! Chaque page peut être délicatement déchirée puis rattachée grâce à une bande auto-agrippante, pour un jeu sans fin qui muscle la motricité fine.",
         "Do the pages really tear?",
         "Yes, that's the whole point of our books! Each page can be gently torn off and reattached with a hook-and-loop strip, for endless play that builds fine motor skills."),
        ("Comment laver un livre en feutrine ?",
         "Nos livres sont lavables en machine à 30°C sur cycle délicat. Nous recommandons un séchage à plat, sans sèche-linge, pour préserver la forme et les couleurs. Nous vous conseillons également de laver le livre une première fois dès sa réception, avant la première utilisation.",
         "How do I wash a felt book?",
         "Our books are machine washable at 30°C on a delicate cycle. We recommend flat drying, without a tumble dryer, to preserve the shape and colours. We also recommend washing the book once as soon as you receive it, before first use."),
        ("Ces livres sont-ils adaptés dès la naissance ?",
         "Oui, tous nos livres conviennent aux bébés dès 6 mois. Pour connaître la tranche d'âge précise, vous pouvez également consulter les recommandations d'âge sur la fiche de chaque produit.",
         "Are these books suitable from birth?",
         "Yes, all our books are suitable for babies aged 6 months and up. For the precise age range, you can also check the age recommendations on each product's page."),
        ("Les livres contiennent-ils des petites pièces dangereuses ?",
         "Non, nos livres sont conçus sans petites pièces détachables dangereuses et respectent les normes de sécurité en vigueur pour la petite enfance.",
         "Do the books contain small, dangerous parts?",
         "No, our books are designed without small dangerous detachable parts and comply with current safety standards for early childhood."),
        ("Les couleurs risquent-elles de déteindre au lavage ?",
         "Nos matières sont sélectionnées pour leur bonne tenue des couleurs. Nous recommandons toutefois un lavage séparé la première fois par précaution.",
         "Might the colours run when washed?",
         "Our materials are selected for good colour fastness. However, we recommend washing separately the first time as a precaution."),
        ("Peut-on emmener ces livres en voyage ?",
         "Tout à fait, ils sont légers, silencieux et incassables : parfaits pour les trajets en voiture, en train ou en avion.",
         "Can these books be taken on trips?",
         "Absolutely, they are light, silent and unbreakable: perfect for car, train or plane journeys."),
        ("Vos livres sont-ils fabriqués en France ?",
         "Notre atelier travaille avec des partenaires sélectionnés pour la qualité de la feutrine et le respect de normes strictes de sécurité ; les informations détaillées de fabrication figurent sur chaque fiche produit.",
         "Are your books made in France?",
         "Our workshop works with partners selected for the quality of their felt and their compliance with strict safety standards; detailed manufacturing information is shown on each product page."),
    ],
    "Compte & retours": [
        ("Comment créer un compte ?",
         "Cliquez sur « Mon compte » puis « Créer un compte », renseignez votre e-mail et un mot de passe. Vous recevrez 10% de réduction sur votre première commande.",
         "How do I create an account?",
         "Click “My account” then “Create an account”, enter your e-mail and a password. You will receive 10% off your first order."),
        ("J'ai oublié mon mot de passe, que faire ?",
         "Cliquez sur « Mot de passe oublié » sur la page de connexion, un e-mail de réinitialisation vous sera envoyé.",
         "I forgot my password, what should I do?",
         "Click “Forgot password” on the login page, and a reset e-mail will be sent to you."),
        ("Comment modifier mes informations personnelles ?",
         "Rendez-vous dans la rubrique « Mon compte » pour mettre à jour votre adresse, votre e-mail ou vos préférences de communication.",
         "How do I update my personal information?",
         "Go to the “My account” section to update your address, e-mail or communication preferences."),
        ("Quelle est votre politique de retour ?",
         "Vous disposez de 14 jours après réception pour nous retourner un article non utilisé, dans son emballage d'origine.",
         "What is your return policy?",
         "You have 14 days after receipt to return an unused item to us in its original packaging."),
        ("Comment effectuer un retour ?",
         "Contactez notre service client à monpremierlivre.com@gmail.com avec votre numéro de commande, nous vous indiquerons la marche à suivre.",
         "How do I make a return?",
         "Contact our customer service at monpremierlivre.com@gmail.com with your order number, and we will explain the steps to follow."),
        ("Les frais de retour sont-ils à ma charge ?",
         "Les frais de retour restent à la charge de la cliente, sauf en cas d'erreur ou de défaut de notre part.",
         "Do I have to pay for return shipping?",
         "Return shipping costs are the customer's responsibility, except in the event of an error or fault on our part."),
        ("Comment me désabonner des e-mails promotionnels ?",
         "Un lien de désabonnement est présent en bas de chaque e-mail, ou vous pouvez modifier vos préférences directement dans votre compte.",
         "How do I unsubscribe from promotional e-mails?",
         "An unsubscribe link is included at the bottom of every e-mail, or you can change your preferences directly in your account."),
        ("Mes données personnelles sont-elles protégées ?",
         "Oui, conformément au RGPD, vos données ne sont jamais revendues et sont utilisées uniquement pour le traitement de vos commandes et, si vous l'acceptez, pour nos communications.",
         "Is my personal data protected?",
         "Yes, in accordance with GDPR, your data is never resold and is only used to process your orders and, if you agree, for our communications."),
        ("Puis-je supprimer mon compte ?",
         "Oui, vous pouvez demander la suppression de votre compte à tout moment en nous contactant par e-mail.",
         "Can I delete my account?",
         "Yes, you can request deletion of your account at any time by contacting us by e-mail."),
    ],
}
