[build]
  publish = "."
  functions = "netlify/functions"
  command = ""

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/api/send-welcome-code"
  to = "/.netlify/functions/send-welcome-code"
  status = 200

[[redirects]]
  from = "/api/notify-new-product"
  to = "/.netlify/functions/notify-new-product"
  status = 200

[[redirects]]
  from = "/api/send-newsletter-blast"
  to = "/.netlify/functions/send-newsletter-blast"
  status = 200
